"""initial_schema

Revision ID: cb9587c43c31
Revises:
Create Date: 2026-10-02 19:14:26.435390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb9587c43c31"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certification",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certification")),
        sa.UniqueConstraint("code", name=op.f("uq_certification_code")),
    )
    op.create_table(
        "country",
        sa.Column("code", sa.CHAR(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_country")),
        sa.UniqueConstraint("name", name=op.f("uq_country_name")),
    )
    op.create_table(
        "currency",
        sa.Column("code", sa.CHAR(length=3), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("minor_units", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currency")),
    )
    op.create_table(
        "incoterm",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("edition_year", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("code", "edition_year", name=op.f("pk_incoterm")),
    )
    op.create_table(
        "permission",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_permission")),
    )
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("name", name=op.f("uq_role_name")),
    )
    op.create_table(
        "unit_of_measure",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_unit_of_measure")),
    )
    op.create_table(
        "app_user",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("photo_file_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_app_user_role_id_role")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
        sa.UniqueConstraint("photo_file_id", name=op.f("uq_app_user_photo_file_id")),
    )
    op.create_index(op.f("ix_app_user_role_id"), "app_user", ["role_id"], unique=False)
    op.create_table(
        "customer",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("contact_name", sa.String(length=160), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("eori_number", sa.String(length=35), nullable=True),
        sa.Column("preferred_currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk_customer_country_code_country"),
        ),
        sa.ForeignKeyConstraint(
            ["preferred_currency_code"],
            ["currency.code"],
            name=op.f("fk_customer_preferred_currency_code_currency"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer")),
        sa.UniqueConstraint("eori_number", name=op.f("uq_customer_eori_number")),
    )
    op.create_table(
        "exchange_rate",
        sa.Column("from_currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("to_currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint("rate > 0", name=op.f("ck_exchange_rate_positive_rate")),
        sa.ForeignKeyConstraint(
            ["from_currency_code"],
            ["currency.code"],
            name=op.f("fk_exchange_rate_from_currency_code_currency"),
        ),
        sa.ForeignKeyConstraint(
            ["to_currency_code"],
            ["currency.code"],
            name=op.f("fk_exchange_rate_to_currency_code_currency"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_rate")),
        sa.UniqueConstraint(
            "from_currency_code",
            "to_currency_code",
            "provider",
            "observed_at",
            name=op.f("uq_exchange_rate_from_currency_code"),
        ),
    )
    op.create_table(
        "product",
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("variety", sa.String(length=120), nullable=False),
        sa.Column("quality_grade", sa.String(length=80), nullable=False),
        sa.Column("hs_code", sa.String(length=20), nullable=True),
        sa.Column("base_unit_code", sa.String(length=12), nullable=False),
        sa.Column(
            "low_stock_threshold", sa.Numeric(precision=18, scale=3), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('coffee', 'cacao')", name=op.f("ck_product_valid_type")
        ),
        sa.CheckConstraint(
            "low_stock_threshold IS NULL OR low_stock_threshold >= 0",
            name=op.f("ck_product_nonnegative_stock_threshold"),
        ),
        sa.ForeignKeyConstraint(
            ["base_unit_code"],
            ["unit_of_measure.code"],
            name=op.f("fk_product_base_unit_code_unit_of_measure"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("permission_code", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permission.code"],
            name=op.f("fk_role_permission_permission_code_permission"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_role_permission_role_id_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_code", name=op.f("pk_role_permission")
        ),
    )
    op.create_table(
        "supplier",
        sa.Column("business_name", sa.String(length=180), nullable=False),
        sa.Column("contact_name", sa.String(length=160), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk_supplier_country_code_country"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier")),
    )
    op.create_table(
        "audit_log",
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb_build_object()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["app_user.id"],
            name=op.f("fk_audit_log_actor_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "cacao_detail",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("bean_type", sa.String(length=100), nullable=False),
        sa.Column(
            "fermentation_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.CheckConstraint(
            "fermentation_percent BETWEEN 0 AND 100",
            name=op.f("ck_cacao_detail_fermentation_range"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_cacao_detail_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_cacao_detail")),
    )
    op.create_table(
        "coffee_detail",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("humidity_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.CheckConstraint(
            "humidity_percent BETWEEN 0 AND 100",
            name=op.f("ck_coffee_detail_humidity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_coffee_detail_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_coffee_detail")),
    )
    op.create_table(
        "customer_order",
        sa.Column("order_number", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_customer_order_created_by_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currency.code"],
            name=op.f("fk_customer_order_currency_code_currency"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("fk_customer_order_customer_id_customer"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_order")),
        sa.UniqueConstraint(
            "order_number", name=op.f("uq_customer_order_order_number")
        ),
    )
    op.create_index(
        "ix_customer_order_customer_status",
        "customer_order",
        ["customer_id", "status"],
        unique=False,
    )
    op.create_table(
        "farm",
        sa.Column("supplier_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90",
            name=op.f("ck_farm_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name=op.f("ck_farm_longitude_range"),
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk_farm_country_code_country"),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["supplier.id"], name=op.f("fk_farm_supplier_id_supplier")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_farm")),
    )
    op.create_index(op.f("ix_farm_supplier_id"), "farm", ["supplier_id"], unique=False)
    op.create_table(
        "password_reset_token",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_password_reset_token_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_token")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("uq_password_reset_token_token_hash")
        ),
    )
    op.create_index(
        op.f("ix_password_reset_token_user_id"),
        "password_reset_token",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "product_certification",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("certification_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["certification_id"],
            ["certification.id"],
            name=op.f("fk_product_certification_certification_id_certification"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_certification_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "product_id", "certification_id", name=op.f("pk_product_certification")
        ),
    )
    op.create_table(
        "stored_file",
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("uploaded_by_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_stored_file_nonnegative_size")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["app_user.id"],
            name=op.f("fk_stored_file_uploaded_by_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_file")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_stored_file_storage_key")),
    )
    op.create_table(
        "background_job",
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_by_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_file_id", sa.BigInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("progress_percent", sa.SmallInteger(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_background_job_nonnegative_attempts")
        ),
        sa.CheckConstraint(
            "progress_percent IS NULL OR progress_percent BETWEEN 0 AND 100",
            name=op.f("ck_background_job_progress_range"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["app_user.id"],
            name=op.f("fk_background_job_requested_by_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["result_file_id"],
            ["stored_file.id"],
            name=op.f("fk_background_job_result_file_id_stored_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_job")),
        sa.UniqueConstraint(
            "result_file_id", name=op.f("uq_background_job_result_file_id")
        ),
    )
    op.create_table(
        "export",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("destination_country_code", sa.CHAR(length=2), nullable=False),
        sa.Column("incoterm_code", sa.String(length=8), nullable=False),
        sa.Column("incoterm_year", sa.SmallInteger(), nullable=False),
        sa.Column("export_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_export_created_by_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["destination_country_code"],
            ["country.code"],
            name=op.f("fk_export_destination_country_code_country"),
        ),
        sa.ForeignKeyConstraint(
            ["incoterm_code", "incoterm_year"],
            ["incoterm.code", "incoterm.edition_year"],
            name=op.f("fk_export_incoterm_code_incoterm"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["customer_order.id"],
            name=op.f("fk_export_order_id_customer_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export")),
    )
    op.create_index(
        "ix_export_order_date", "export", ["order_id", "export_date"], unique=False
    )
    op.create_table(
        "order_line",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_order_line_positive_quantity")
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_order_line_nonnegative_unit_price")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["customer_order.id"],
            name=op.f("fk_order_line_order_id_customer_order"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_order_line_product_id_product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_line")),
    )
    op.create_index(
        op.f("ix_order_line_order_id"), "order_line", ["order_id"], unique=False
    )
    op.create_index("ix_order_line_product", "order_line", ["product_id"], unique=False)
    op.create_table(
        "payment_obligation",
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_due", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency_code", sa.CHAR(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "amount_due > 0", name=op.f("ck_payment_obligation_positive_amount_due")
        ),
        sa.ForeignKeyConstraint(
            ["currency_code"],
            ["currency.code"],
            name=op.f("fk_payment_obligation_currency_code_currency"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["customer_order.id"],
            name=op.f("fk_payment_obligation_order_id_customer_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_obligation")),
    )
    op.create_index(
        op.f("ix_payment_obligation_due_date"),
        "payment_obligation",
        ["due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_obligation_order_id"),
        "payment_obligation",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "product_lot",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("farm_id", sa.BigInteger(), nullable=False),
        sa.Column("lot_code", sa.String(length=80), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["farm_id"], ["farm.id"], name=op.f("fk_product_lot_farm_id_farm")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_lot_product_id_product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_lot")),
        sa.UniqueConstraint("farm_id", "lot_code", name=op.f("uq_product_lot_farm_id")),
    )
    op.create_index(
        "ix_product_lot_farm_product",
        "product_lot",
        ["farm_id", "product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_lot_product_id"), "product_lot", ["product_id"], unique=False
    )
    op.create_table(
        "export_document",
        sa.Column("export_id", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["app_user.id"],
            name=op.f("fk_export_document_created_by_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["export_id"],
            ["export.id"],
            name=op.f("fk_export_document_export_id_export"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["stored_file.id"],
            name=op.f("fk_export_document_file_id_stored_file"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_document")),
    )
    op.create_index(
        op.f("ix_export_document_export_id"),
        "export_document",
        ["export_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_export_document_file_id"), "export_document", ["file_id"], unique=False
    )
    op.create_table(
        "export_line",
        sa.Column("export_id", sa.BigInteger(), nullable=False),
        sa.Column("order_line_id", sa.BigInteger(), nullable=False),
        sa.Column("product_lot_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("hs_code_snapshot", sa.String(length=20), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_export_line_positive_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["export_id"], ["export.id"], name=op.f("fk_export_line_export_id_export")
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_line.id"],
            name=op.f("fk_export_line_order_line_id_order_line"),
        ),
        sa.ForeignKeyConstraint(
            ["product_lot_id"],
            ["product_lot.id"],
            name=op.f("fk_export_line_product_lot_id_product_lot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_line")),
    )
    op.create_index(
        op.f("ix_export_line_export_id"), "export_line", ["export_id"], unique=False
    )
    op.create_table(
        "notification",
        sa.Column("recipient_user_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("product_lot_id", sa.BigInteger(), nullable=True),
        sa.Column("payment_obligation_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column("dedupe_key", sa.String(length=180), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "(type = 'low_stock' AND product_lot_id IS NOT NULL AND payment_obligation_id IS NULL) OR (type = 'payment_due' AND payment_obligation_id IS NOT NULL AND product_lot_id IS NULL)",
            name=op.f("ck_notification_type_target_match"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_obligation_id"],
            ["payment_obligation.id"],
            name=op.f("fk_notification_payment_obligation_id_payment_obligation"),
        ),
        sa.ForeignKeyConstraint(
            ["product_lot_id"],
            ["product_lot.id"],
            name=op.f("fk_notification_product_lot_id_product_lot"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["app_user.id"],
            name=op.f("fk_notification_recipient_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_notification_dedupe_key")),
    )
    op.create_index(
        "ix_notification_recipient_read_created",
        "notification",
        ["recipient_user_id", "read_at", "created_at"],
        unique=False,
    )
    op.create_table(
        "outbox_message",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_outbox_message_nonnegative_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["background_job.id"],
            name=op.f("fk_outbox_message_job_id_background_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_message")),
        sa.UniqueConstraint("job_id", name=op.f("uq_outbox_message_job_id")),
    )
    op.create_table(
        "payment_transaction",
        sa.Column("obligation_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exchange_rate_id", sa.BigInteger(), nullable=True),
        sa.Column("recorded_by_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "amount > 0", name=op.f("ck_payment_transaction_positive_amount")
        ),
        sa.ForeignKeyConstraint(
            ["exchange_rate_id"],
            ["exchange_rate.id"],
            name=op.f("fk_payment_transaction_exchange_rate_id_exchange_rate"),
        ),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["payment_obligation.id"],
            name=op.f("fk_payment_transaction_obligation_id_payment_obligation"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["app_user.id"],
            name=op.f("fk_payment_transaction_recorded_by_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_transaction")),
    )
    op.create_index(
        op.f("ix_payment_transaction_obligation_id"),
        "payment_transaction",
        ["obligation_id"],
        unique=False,
    )
    op.create_table(
        "shipment",
        sa.Column("export_id", sa.BigInteger(), nullable=False),
        sa.Column("carrier", sa.String(length=160), nullable=False),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["export_id"], ["export.id"], name=op.f("fk_shipment_export_id_export")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment")),
    )
    op.create_index(
        op.f("ix_shipment_export_id"), "shipment", ["export_id"], unique=False
    )
    op.create_table(
        "inventory_movement",
        sa.Column("product_lot_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("reason", sa.String(length=30), nullable=False),
        sa.Column("order_line_id", sa.BigInteger(), nullable=True),
        sa.Column("export_line_id", sa.BigInteger(), nullable=True),
        sa.Column("performed_by_id", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "NOT (order_line_id IS NOT NULL AND export_line_id IS NOT NULL)",
            name=op.f("ck_inventory_movement_single_source"),
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0",
            name=op.f("ck_inventory_movement_nonzero_quantity_delta"),
        ),
        sa.ForeignKeyConstraint(
            ["export_line_id"],
            ["export_line.id"],
            name=op.f("fk_inventory_movement_export_line_id_export_line"),
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_line.id"],
            name=op.f("fk_inventory_movement_order_line_id_order_line"),
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_id"],
            ["app_user.id"],
            name=op.f("fk_inventory_movement_performed_by_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["product_lot_id"],
            ["product_lot.id"],
            name=op.f("fk_inventory_movement_product_lot_id_product_lot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movement")),
    )
    op.create_index(
        "ix_inventory_movement_lot_occurred",
        "inventory_movement",
        ["product_lot_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "shipment_event",
        sa.Column("shipment_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("recorded_by_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["app_user.id"],
            name=op.f("fk_shipment_event_recorded_by_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
            name=op.f("fk_shipment_event_shipment_id_shipment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_event")),
    )
    op.create_index(
        "ix_shipment_event_shipment_occurred",
        "shipment_event",
        ["shipment_id", "occurred_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_app_user_photo_file_id_stored_file",
        "app_user",
        "stored_file",
        ["photo_file_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_shipment_event_shipment_occurred", table_name="shipment_event")
    op.drop_table("shipment_event")
    op.drop_index("ix_inventory_movement_lot_occurred", table_name="inventory_movement")
    op.drop_table("inventory_movement")
    op.drop_index(op.f("ix_shipment_export_id"), table_name="shipment")
    op.drop_table("shipment")
    op.drop_index(
        op.f("ix_payment_transaction_obligation_id"), table_name="payment_transaction"
    )
    op.drop_table("payment_transaction")
    op.drop_table("outbox_message")
    op.drop_index("ix_notification_recipient_read_created", table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_export_line_export_id"), table_name="export_line")
    op.drop_table("export_line")
    op.drop_index(op.f("ix_export_document_file_id"), table_name="export_document")
    op.drop_index(op.f("ix_export_document_export_id"), table_name="export_document")
    op.drop_table("export_document")
    op.drop_index(op.f("ix_product_lot_product_id"), table_name="product_lot")
    op.drop_index("ix_product_lot_farm_product", table_name="product_lot")
    op.drop_table("product_lot")
    op.drop_index(
        op.f("ix_payment_obligation_order_id"), table_name="payment_obligation"
    )
    op.drop_index(
        op.f("ix_payment_obligation_due_date"), table_name="payment_obligation"
    )
    op.drop_table("payment_obligation")
    op.drop_index("ix_order_line_product", table_name="order_line")
    op.drop_index(op.f("ix_order_line_order_id"), table_name="order_line")
    op.drop_table("order_line")
    op.drop_index("ix_export_order_date", table_name="export")
    op.drop_table("export")
    op.drop_table("background_job")
    op.drop_constraint(
        "fk_app_user_photo_file_id_stored_file", "app_user", type_="foreignkey"
    )
    op.drop_table("stored_file")
    op.drop_table("product_certification")
    op.drop_index(
        op.f("ix_password_reset_token_user_id"), table_name="password_reset_token"
    )
    op.drop_table("password_reset_token")
    op.drop_index(op.f("ix_farm_supplier_id"), table_name="farm")
    op.drop_table("farm")
    op.drop_index("ix_customer_order_customer_status", table_name="customer_order")
    op.drop_table("customer_order")
    op.drop_table("coffee_detail")
    op.drop_table("cacao_detail")
    op.drop_table("audit_log")
    op.drop_table("supplier")
    op.drop_table("role_permission")
    op.drop_table("product")
    op.drop_table("exchange_rate")
    op.drop_table("customer")
    op.drop_index(op.f("ix_app_user_role_id"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_table("unit_of_measure")
    op.drop_table("role")
    op.drop_table("permission")
    op.drop_table("incoterm")
    op.drop_table("currency")
    op.drop_table("country")
    op.drop_table("certification")
    # ### end Alembic commands ###
